groups:
- name: Cinder
  rules:
    - alert: CinderStateWarning
      expr: openstack_cinder_agent_state{adminState="disabled"} == 0
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: Cinder service disabled. (Instance {{ $labels.hostname }})
        description: |
          The Cinder service is currently disabled on host {{ $labels.hostname }}.
            LABELS = {{ $labels }}

    - alert: CinderStateCritical
      expr: openstack_cinder_agent_state{adminState="down"} == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: Cinder service down. (Instance {{ $labels.hostname }})
        description: |
          The Cinder service is currently down on host {{ $labels.hostname }}.
            LABELS = {{ $labels }}
