name: Check File Updates

on:
  workflow_call:

jobs:

  check-file-updates:
    name: Check updates for files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout local repository
        uses: actions/checkout@v4
      - name: Check differences
        run: make check-dashboard-updates
