name: Upload and Release Charm

on:
  push:
    branches: [main]

concurrency:
  group: release-to-edge
  cancel-in-progress: true

jobs:
  check-code-quality:
    name: Run charm code quality checks
    uses: ./.github/workflows/_quality_check.yaml
    secrets: inherit
    with:
      tox-version: ""  # latest tox
      python-version: "3.10"

  release-to-edge:
    needs: [check-code-quality]
    name: Release charm to latest/edge channel
    uses: ./.github/workflows/_release.yaml
    secrets: inherit
    with:
      channel: "latest/edge"
